<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { ArrowUpDown, BookOpenText, RefreshCw } from "@lucide/vue"; import { adminApi } from "../api/admin.api"; import type { TopicStats } from "../types"; import StatePanel from "../components/StatePanel.vue"; import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"; import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Skeleton } from "@/components/ui/skeleton"; import { Spinner } from "@/components/ui/spinner"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
const topics = ref<TopicStats[]>([]); const loading = ref(true); const error = ref(false); const activeFilter = ref("all"); const sort = ref<{key:keyof TopicStats; direction:1|-1}>({key:"timesSent",direction:-1});
const shown = computed(() => topics.value.filter((row) => activeFilter.value === "all" || row.isActive === (activeFilter.value === "active")).sort((a,b) => String(a[sort.value.key] ?? "").localeCompare(String(b[sort.value.key] ?? ""), "ru", {numeric:true}) * sort.value.direction));
function changeSort(key:keyof TopicStats){sort.value={key,direction:sort.value.key===key&&sort.value.direction===1?-1:1};}
async function load(){loading.value=true;error.value=false;try{topics.value=await adminApi.getTopics();}catch{error.value=true;}finally{loading.value=false;}} onMounted(load);
</script>
<template><section class="flex flex-col gap-6"><header class="page-header"><div><p class="eyebrow">Аналитика</p><h1>Статистика по темам</h1><p>Эффективность и вовлечённость для каждого направления.</p></div><div class="header-actions"><Select v-model="activeFilter"><SelectTrigger aria-label="Фильтр активности"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="all">Все темы</SelectItem><SelectItem value="active">Активные</SelectItem><SelectItem value="inactive">Неактивные</SelectItem></SelectGroup></SelectContent></Select><Button variant="outline" :disabled="loading" @click="load"><Spinner v-if="loading" data-icon="inline-start"/><RefreshCw v-else data-icon="inline-start"/>Обновить</Button></div></header>
<StatePanel v-if="error&&!loading" title="Не удалось загрузить темы" retry-label="Повторить" @retry="load"/><div v-else class="overflow-hidden rounded-xl border bg-card text-card-foreground"><div class="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Тема</TableHead><TableHead>Статус</TableHead><TableHead v-for="column in [{key:'timesSent',label:'Отправлено'},{key:'responsesCount',label:'Ответов'},{key:'responseRate',label:'Конверсия'},{key:'averageScore',label:'Ср. оценка'}]" :key="column.key"><Button variant="ghost" size="sm" @click="changeSort(column.key as keyof TopicStats)">{{column.label}}<ArrowUpDown data-icon="inline-end"/></Button></TableHead></TableRow></TableHeader><TableBody v-if="loading"><TableRow v-for="i in 5" :key="i"><TableCell v-for="j in 6" :key="j"><Skeleton class="h-5 w-full"/></TableCell></TableRow></TableBody><TableBody v-else><TableRow v-for="row in shown" :key="row.id"><TableCell class="font-medium">{{row.topic}}</TableCell><TableCell><Badge :variant="row.isActive?'default':'secondary'">{{row.isActive?'Активна':'Неактивна'}}</Badge></TableCell><TableCell>{{row.timesSent}}</TableCell><TableCell>{{row.responsesCount}}</TableCell><TableCell>{{row.responseRate}}%</TableCell><TableCell><Badge variant="outline">{{row.averageScore!==null?`${row.averageScore}/10`:'Нет данных'}}</Badge></TableCell></TableRow></TableBody></Table><Empty v-if="!loading&&!shown.length"><EmptyHeader><EmptyMedia variant="icon"><BookOpenText/></EmptyMedia><EmptyTitle>Статистики пока нет</EmptyTitle><EmptyDescription>Для выбранного фильтра данные отсутствуют.</EmptyDescription></EmptyHeader></Empty></div></div></section></template>
