<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage, ElMessageBox } from "element-plus";
import { adminApi } from "../api/admin.api";
import type { UserDetail } from "../types";
import IconSymbol from "../components/IconSymbol.vue";
import StatePanel from "../components/StatePanel.vue";
const levels = ["A1", "A2", "B1", "B2", "C1", "C2"];
const route = useRoute(); const router = useRouter(); const user = ref<UserDetail | null>(null); const loading = ref(true); const error = ref(false); const action = ref<string | null>(null); const banOpen = ref(false); const banReason = ref("");
const id = computed(() => String(route.params.id)); const banned = computed(() => user.value?.status === "banned"); const formatDate = (value: string) => new Date(value).toLocaleString("ru-RU");
const responsePage = ref(1); const responsePageSize = 10;
const paginatedResponses = computed(() => user.value?.responses.slice((responsePage.value - 1) * responsePageSize, responsePage.value * responsePageSize) ?? []);
async function load() { loading.value = true; error.value = false; try { user.value = await adminApi.getUserById(id.value); responsePage.value = 1; } catch { error.value = true; user.value = null; } finally { loading.value = false; } }
async function update(key: string, data: Parameters<typeof adminApi.updateUser>[1], success: string) { action.value = key; try { user.value = await adminApi.updateUser(id.value, data); ElMessage.success(success); } catch { ElMessage.error("Не удалось обновить пользователя"); } finally { action.value = null; } }
async function changeLevel(level: string | null | undefined) { await update("level", { languageLevel: level ?? null }, "Уровень обновлён"); }
async function toggleDaily() { if (user.value) await update("daily", { dailyPromptEnabled: !user.value.dailyPromptEnabled }, "Настройки рассылки обновлены"); }
async function ban() { await update("ban", { status: "banned", bannedReason: banReason.value.trim() || undefined }, "Пользователь заблокирован"); if (user.value?.status === "banned") { banOpen.value = false; banReason.value = ""; } }
async function unban() { try { await ElMessageBox.confirm("Разблокировать пользователя?", "Подтверждение", { confirmButtonText: "Разблокировать", cancelButtonText: "Отмена" }); } catch { return; } await update("unban", { status: "active" }, "Пользователь разблокирован"); }
async function resetProgress() { try { await ElMessageBox.confirm("Все ответы и история пользователя будут удалены. Это действие нельзя отменить.", "Сбросить прогресс?", { type: "warning", confirmButtonText: "Сбросить", cancelButtonText: "Отмена" }); } catch { return; } action.value = "reset"; try { await adminApi.resetUserProgress(id.value); await load(); ElMessage.success("Прогресс сброшен"); } catch { ElMessage.error("Не удалось сбросить прогресс"); } finally { action.value = null; } }
onMounted(load);
</script>
<template>
  <section><el-button class="back-button" text @click="router.push('/users')"><IconSymbol name="back" />К пользователям</el-button>
    <div v-if="loading" class="detail-loading"><el-skeleton animated :rows="8" /></div>
    <StatePanel v-else-if="error || !user" title="Пользователь не найден" description="Не удалось получить данные пользователя." retry-label="Повторить" @retry="load" />
    <template v-else><header class="page-header user-header"><div><p class="eyebrow">Карточка пользователя</p><h1>{{ user.username || `Пользователь ${user.telegramId}` }} <el-tag v-if="banned" type="danger">Заблокирован</el-tag></h1><p>Telegram ID: {{ user.telegramId }}</p></div><div class="header-actions user-actions"><el-select :model-value="user.languageLevel || undefined" clearable placeholder="Уровень" aria-label="Уровень языка" :disabled="action !== null" @change="changeLevel"><el-option v-for="level in levels" :key="level" :label="level" :value="level" /></el-select><el-button :type="user.dailyPromptEnabled ? 'default' : 'primary'" :loading="action === 'daily'" :disabled="action !== null" @click="toggleDaily">{{ user.dailyPromptEnabled ? 'Выключить рассылку' : 'Включить рассылку' }}</el-button><el-button v-if="banned" :loading="action === 'unban'" :disabled="action !== null" @click="unban">Разблокировать</el-button><el-button v-else type="danger" plain :disabled="action !== null" @click="banOpen = true">Заблокировать</el-button><el-button type="danger" plain :loading="action === 'reset'" :disabled="action !== null" @click="resetProgress">Сбросить прогресс</el-button></div></header>
      <div class="info-card"><dl class="details-grid"><div><dt>Имя пользователя</dt><dd>{{ user.username || '—' }}</dd></div><div><dt>Рассылка</dt><dd><el-tag :type="user.dailyPromptEnabled ? 'success' : 'info'">{{ user.dailyPromptEnabled ? 'Включена' : 'Выключена' }}</el-tag></dd></div><div><dt>Время рассылки</dt><dd>{{ String(user.dailyPromptHour).padStart(2, '0') }}:{{ String(user.dailyPromptMinute).padStart(2, '0') }}</dd></div><div><dt>Часовой пояс</dt><dd>{{ user.timezone }}</dd></div><div><dt>Уровень языка</dt><dd>{{ user.languageLevel || '—' }}</dd></div><div><dt>Регистрация</dt><dd>{{ formatDate(user.createdAt) }}</dd></div><div><dt>Получено промптов</dt><dd>{{ user.promptsReceived }}</dd></div><div><dt>Ответов</dt><dd>{{ user.responsesCount }}</dd></div><div><dt>Средняя оценка</dt><dd>{{ user.averageScore !== null ? `${user.averageScore}/10` : '—' }}</dd></div><div v-if="user.bannedAt"><dt>Заблокирован</dt><dd>{{ formatDate(user.bannedAt) }}</dd></div><div v-if="user.bannedReason" class="details-grid__wide"><dt>Причина блокировки</dt><dd>{{ user.bannedReason }}</dd></div></dl></div>
      <div class="section-heading"><h2>Ответы</h2><span>{{ user.responses.length }}</span></div><div class="table-card"><el-table :data="paginatedResponses" row-key="id" stripe table-layout="auto" empty-text="Пользователь пока не отправлял ответы"><el-table-column prop="promptTopic" label="Тема" min-width="160" /><el-table-column prop="overallScore" label="Оценка" width="110"><template #default="{ row }"><el-tag v-if="row.overallScore !== null" :type="row.overallScore >= 7 ? 'success' : row.overallScore >= 5 ? 'warning' : 'danger'">{{ row.overallScore }}/10</el-tag><span v-else>—</span></template></el-table-column><el-table-column prop="transcript" label="Транскрипция" min-width="320" show-overflow-tooltip><template #default="{ row }">{{ row.transcript || '—' }}</template></el-table-column><el-table-column prop="createdAt" label="Дата" min-width="180"><template #default="{ row }">{{ formatDate(row.createdAt) }}</template></el-table-column></el-table><div v-if="user.responses.length > responsePageSize" class="pagination"><el-pagination v-model:current-page="responsePage" background layout="prev, pager, next" :page-size="responsePageSize" :total="user.responses.length" /></div></div>
    </template>
    <el-dialog v-model="banOpen" title="Заблокировать пользователя" width="min(520px, 94vw)" :close-on-click-modal="action !== 'ban'"><p class="dialog-copy">При необходимости укажите причину — она будет видна в карточке пользователя.</p><el-input v-model="banReason" type="textarea" :rows="3" maxlength="500" show-word-limit placeholder="Причина блокировки (необязательно)" /><template #footer><el-button :disabled="action === 'ban'" @click="banOpen = false">Отмена</el-button><el-button type="danger" :loading="action === 'ban'" :disabled="action === 'ban'" @click="ban">Заблокировать</el-button></template></el-dialog>
  </section>
</template>
